language: python
python: 3.6
script:
    - mkdir ~/.aws
    - echo "[default]\nregion=eu-west-2" > ~/.aws/config
deploy:
    provider: script
    script: zappa update production
    on:
        branch: master
